workflows:
  Default Workflow:
    name: Default Workflow
    environment:
      flutter: 3.22.2
      java: 17
    scripts:
      - name: Fix Android - recreate gradle
        script: |
          rm -rf android
          flutter create. --platforms=android --project-name roster_pro --org com.example.rosterpro
          flutter pub get
          echo "SHA1 for Google Console"
          keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android | grep SHA1 || true
      - name: Build APK
        script: flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/**/outputs/**/*.apk
