workflows:
  Default Workflow:
    name: Default Workflow
    environment:
      flutter: 3.22.2
      java: 17
    scripts:
      - name: Fix Android - recreate gradle
        script: |
          echo "Fixing Gradle"
          rm -rf android
          flutter create. --platforms=android --project-name roster_pro --org com.example.rosterpro
          flutter pub get
      - name: Build APK
        script: flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/**/outputs/**/*.apk
