name: roster_pro
description: Roster Pro v6.28 fix all 7
publish_to: 'none'
version: 6.28.0+28
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  file_picker: ^8.0.0
  path_provider: ^2.1.5
flutter:
  uses-material-design: true
