import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';
void main(){runApp(const RosterApp());}
class ShiftDef{String code;String label;double hours;double allowance;double ot;Color color;ShiftDef(this.code,this.label,this.hours,this.color,{this.allowance=0,this.ot=0}); Map<String,dynamic> toJson()=>{'code':code,'label':label,'hours':hours,'allowance':allowance,'ot':ot,'color':color.value}; factory ShiftDef.fromJson(Map<String,dynamic> j)=>ShiftDef(j['code'],j['label']??j['code'],(j['hours']??8).toDouble(),Color(j['color']??0xFFFF9800),allowance:(j['allowance']??0).toDouble(),ot:(j['ot']??0).toDouble());}
class RosterApp extends StatelessWidget{const RosterApp({super.key}); @override Widget build(BuildContext context){return MaterialApp(title:'Roster Pro v6.24',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.deepPurple),home:const MainPage());}}
class MainPage extends StatefulWidget{const MainPage({super.key}); @override State<MainPage> createState()=>MainPageState();}
class MainPageState extends State<MainPage>{
int tab=0; DateTime focused=DateTime.now(); DateTime selectedDay=DateTime.now();
Map<String,String> roster={}; Map<String,String> rosterNote={}; Map<String,ShiftDef> defs={'早':ShiftDef('早','早更 07:00-15:30',8,Colors.orange),'中':ShiftDef('中','中更',8,Colors.blue),'宵':ShiftDef('宵','宵更',8,Colors.purple,allowance:60),'O':ShiftDef('O','休',0,Colors.green),'早收':ShiftDef('早收','早收長代號',8,Colors.orange),};
List<List<String>> pattern=[["早","早","中","中","宵","宵","O"],["早","早","早","中","中","O","O"]]; double carry=0;
@override void initState(){super.initState();load();}
Future<void> load() async{var sp=await SharedPreferences.getInstance();var r=sp.getString('roster'); if(r!=null) roster=Map<String,String>.from(jsonDecode(r)); var rn=sp.getString('note'); if(rn!=null) rosterNote=Map<String,String>.from(jsonDecode(rn)); setState((){});}
Future<void> save() async{var sp=await SharedPreferences.getInstance();sp.setString('roster',jsonEncode(roster)); sp.setString('note',jsonEncode(rosterNote));}
int isoWeek(DateTime d){var jan1=DateTime(d.year,1,1); return 1+((d.difference(jan1).inDays+jan1.weekday-1)/7).floor();}
Widget calTab(){
DateTime first=DateTime(focused.year,focused.month,1); DateTime start=first.subtract(Duration(days:first.weekday-1)); List<DateTime> days=List.generate(42,(i)=>start.add(Duration(days:i)));
String selKey=DateFormat('yyyy-MM-dd').format(selectedDay);
return Column(children:[
Padding(padding:const EdgeInsets.all(12),child:Row(children:[const Icon(Icons.calendar_month),const SizedBox(width:8),Text('${focused.year}年${focused.month}月',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const Spacer(),IconButton(icon:const Icon(Icons.chevron_left),onPressed:(){setState(()=>focused=DateTime(focused.year,focused.month-1,1));}),IconButton(icon:const Icon(Icons.chevron_right),onPressed:(){setState(()=>focused=DateTime(focused.year,focused.month+1,1));}),FilledButton.tonal(onPressed:(){setState((){focused=DateTime.now(); selectedDay=DateTime.now();});},child:const Text('📍今天'))])),
Row(children:const [Expanded(child:Text('Mon',textAlign:TextAlign.center)),Expanded(child:Text('Tue',textAlign:TextAlign.center)),Expanded(child:Text('Wed',textAlign:TextAlign.center)),Expanded(child:Text('Thu',textAlign:TextAlign.center)),Expanded(child:Text('Fri',textAlign:TextAlign.center)),Expanded(child:Text('Sat',textAlign:TextAlign.center)),Expanded(child:Text('Sun',textAlign:TextAlign.center))]),
Expanded(child:GridView.builder(padding:const EdgeInsets.all(6),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:7,childAspectRatio:0.78,mainAxisSpacing:6,crossAxisSpacing:6),itemCount:42,itemBuilder:(ctx,idx){
DateTime day=days[idx]; bool inM=day.month==focused.month; String k=DateFormat('yyyy-MM-dd').format(day); String? code=roster[k]; var def=code!=null?defs[code]:null; bool sel=k==selKey; String w=idx%7==0?'W${isoWeek(day)}':''; Color bg=!inM?const Color(0xFFF5F5F0):sel?Colors.white:def!=null?def.color.withOpacity(0.15):const Color(0xFFFFF0D0); if(code=='O') bg=const Color(0xFFE0F2E9);
return GestureDetector(onTap:(){setState(()=>selectedDay=day); showDetail(day);},child:Container(decoration:BoxDecoration(color:bg,borderRadius:BorderRadius.circular(16),border:sel?Border.all(width:2):null),child:Stack(children:[if(w.isNotEmpty) Positioned(left:6,top:4,child:Text(w,style:const TextStyle(fontSize:9,fontWeight:FontWeight.bold,color:Colors.brown))),Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text('${day.day}',style:TextStyle(fontWeight:FontWeight.bold,color:inM?Colors.black:Colors.grey)),if(code!=null) Container(margin:const EdgeInsets.only(top:4),padding:const EdgeInsets.symmetric(horizontal:8,vertical:2),decoration:BoxDecoration(color:def?.color??Colors.orange,borderRadius:BorderRadius.circular(10)),child:Text(code,style:const TextStyle(color:Colors.white,fontSize:12)))]))]))); })),
Container(padding:const EdgeInsets.all(12),color:Colors.white,child:Row(children:[Expanded(child:Text('${DateFormat('MM/dd EEE').format(selectedDay)} ${roster[selKey]??''} ${rosterNote[selKey]??'哈哈'}',style:const TextStyle(fontSize:16,fontWeight:FontWeight.bold))),FilledButton(onPressed:(){showDetail(selectedDay);},child:const Text('編輯'))])),
]);
}
void showDetail(DateTime day){String k=DateFormat('yyyy-MM-dd').format(day); String cur=roster[k]??''; TextEditingController nc=TextEditingController(text:rosterNote[k]??''); showModalBottomSheet(context:context,builder:(ctx){return StatefulBuilder(builder:(ctx2,setM){return Padding(padding:const EdgeInsets.all(16),child:Column(mainAxisSize:MainAxisSize.min,children:[Text(DateFormat('yyyy-MM-dd EEE').format(day),style:const TextStyle(fontWeight:FontWeight.bold,fontSize:18)),Wrap(spacing:8,children:defs.keys.map((c){return ChoiceChip(label:Text(c),selected:cur==c,onSelected:(_){setM(()=>cur=c);});}).toList()),TextField(controller:nc,decoration:const InputDecoration(labelText:'記事 哈哈')),const SizedBox(height:12),FilledButton(onPressed:(){setState((){if(cur!=''){roster[k]=cur; rosterNote[k]=nc.text;}}); save(); Navigator.pop(ctx2);},child:const Text('儲存'))]));});});}
Widget patternTab(){return Column(children:[Padding(padding:const EdgeInsets.all(12),child:Row(children:[const Text('排更模式 7天 x 自定行數',style:TextStyle(fontWeight:FontWeight.bold)),const Spacer(),FilledButton(onPressed:(){setState(()=>pattern.add(List.filled(7,'O'))); save();},child:const Text('加一行'))])),Expanded(child:ListView.builder(itemCount:pattern.length,itemBuilder:(ctx,r){return Row(children:[SizedBox(width:24,child:Text('${r+1}')),Expanded(child:Row(children:List.generate(7,(c){String code=pattern[r][c]; var d=defs[code]; return Expanded(child:GestureDetector(onTap:(){showModalBottomSheet(context:context,builder:(ctx){return Column(mainAxisSize:MainAxisSize.min,children:defs.keys.map((k)=>ListTile(title:Text(k),onTap:(){setState(()=>pattern[r][c]=k); save(); Navigator.pop(ctx);})).toList());});},child:Container(margin:const EdgeInsets.all(2),height:40,decoration:BoxDecoration(color:d!=null?d.color.withOpacity(0.3):Colors.white,border:Border.all(color:Colors.grey.shade300),borderRadius:BorderRadius.circular(8)),child:Center(child:Text(code)))));}))),IconButton(icon:const Icon(Icons.delete_outline),onPressed:(){setState(()=>pattern.removeAt(r)); save();})]);})),Padding(padding:const EdgeInsets.all(12),child:FilledButton.icon(onPressed:(){DateTime s=DateTime(focused.year,focused.month,1); DateTime e=DateTime(focused.year,focused.month+1,0); List<String> flat=pattern.expand((x)=>x).toList(); int idx=0; for(int i=0;i<=e.difference(s).inDays;i++){String k=DateFormat('yyyy-MM-dd').format(s.add(Duration(days:i))); roster[k]=flat[idx%flat.length]; idx++;} save(); setState(()=>tab=0); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('已自動排班')));},icon:const Icon(Icons.play_arrow),label:const Text('按指定日期自動排班'),style:FilmedButtonStyle())),]);}
FilmedButtonStyle(){return FilledButton.styleFrom(minimumSize:const Size(double.infinity,50));}
Widget reportTab(){int dim=DateTime(focused.year,focused.month+1,0).day; Map<String,int> cnt={}; double hrs=0,allow=0,ot=0; for(int i=1;i<=dim;i++){String k=DateFormat('yyyy-MM-dd').format(DateTime(focused.year,focused.month,i)); String? c=roster[k]; if(c==null) continue; cnt[c]=(cnt[c]??0)+1; var d=defs[c]; if(d!=null){hrs+=d.hours; allow+=d.allowance; ot+=d.ot;}} return ListView(padding:const EdgeInsets.all(12),children:[Text('${focused.year}年${focused.month}月 報表',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),Card(child:ListTile(title:const Text('本月班次統計'),subtitle:Text(cnt.entries.map((e)=>'${e.key}x${e.value}').join(' ')))),Card(color:const Color(0xFFE3F2FD),child:ListTile(title:Text('總工時 ${hrs}h'),subtitle:Text('餘額 ${carry+hrs}h'))),Card(color:const Color(0xFFE8F5E9),child:ListTile(title:Text('津貼總額 \$${allow}'))),Card(color:const Color(0xFFFCE4EC),child:ListTile(title:Text('OT總計 ${ot}h')))]);}
@override Widget build(BuildContext context){return Scaffold(body:[calTab(),patternTab(),reportTab()][tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const [NavigationDestination(icon:Icon(Icons.calendar_month),label:'月曆'),NavigationDestination(icon:Icon(Icons.pattern),label:'模式'),NavigationDestination(icon:Icon(Icons.bar_chart),label:'報表')]));}
}
