import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:file_picker/file_picker.dart';
import 'package:path_provider/path_provider.dart';
void main(){runApp(const RosterApp());}
class ShiftDef{String code;String label;double hours;double allowance;double ot;Color color;ShiftDef(this.code,this.label,this.hours,this.color,{this.allowance=0,this.ot=0});Map<String,dynamic> toJson()=>{'code':code,'label':label,'hours':hours,'allowance':allowance,'ot':ot,'color':color.value};factory ShiftDef.fromJson(Map<String,dynamic> j)=>ShiftDef(j['code'],j['label']??j['code'],(j['hours']??8).toDouble(),Color(j['color']??0xFFFF9800),allowance:(j['allowance']??0).toDouble(),ot:(j['ot']??0).toDouble());}
class RosterApp extends StatelessWidget{const RosterApp({super.key});@override Widget build(BuildContext c){return MaterialApp(title:'Roster Pro v6.28',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.deepPurple),home:const MainPage());}}
const Map<String,String> hkHolidays={'2025-01-01':'元旦','2025-01-29':'年初一','2025-10-07':'中秋翌日','2026-01-01':'元旦','2026-02-17':'年初一','2026-09-26':'中秋翌日','2026-10-01':'國慶','2026-12-25':'聖誕'};
class MainPage extends StatefulWidget{const MainPage({super.key});@override State<MainPage> createState()=>MainPageState();}
class MainPageState extends State<MainPage>{
int tab=0;DateTime focused=DateTime.now();DateTime selectedDay=DateTime.now();
Map<String,String> roster={};Map<String,String> rosterNote={};
Map<String,ShiftDef> defs={'早':ShiftDef('早','早更 07:00-15:30',8,Colors.orange),'中':ShiftDef('中','中更',8,Colors.blue),'宵':ShiftDef('宵','宵更',8,Colors.purple,allowance:60),'O':ShiftDef('O','休',0,Colors.green),'早收':ShiftDef('早收','早收長代號',8,Colors.orange),};
List<List<String>> pattern=[["早","早","中","中","宵","宵","O"],["早","早","早","中","中","O","O"]];
List<Map<String,dynamic>> savedPatterns=[];double carry=0;String customName='我的排更';TextEditingController nameCtrl=TextEditingController();double standardWeeklyHours=44;
@override void initState(){super.initState();load();}
Future<void> load() async{var sp=await SharedPreferences.getInstance();var r=sp.getString('roster');if(r!=null)roster=Map<String,String>.from(jsonDecode(r));var rn=sp.getString('note');if(rn!=null)rosterNote=Map<String,String>.from(jsonDecode(rn));var d=sp.getString('defs');if(d!=null){try{var m=Map<String,dynamic>.from(jsonDecode(d));defs=m.map((k,v)=>MapEntry(k,ShiftDef.fromJson(v)));}catch(_){}}var p=sp.getString('pattern');if(p!=null){try{var l=jsonDecode(p) as List;pattern=l.map<List<String>>((row)=>(row as List).map<String>((e)=>e.toString()).toList()).toList();}catch(_){}}var spats=sp.getString('savedPatterns');if(spats!=null){try{savedPatterns=(jsonDecode(spats) as List).map<Map<String,dynamic>>((e)=>Map<String,dynamic>.from(e)).toList();}catch(_){}}setState((){carry=sp.getDouble('carry')??0;customName=sp.getString('cName')??'我的排更';nameCtrl.text=customName;standardWeeklyHours=sp.getDouble('stdWeek')??44;});}
Future<void> save() async{var sp=await SharedPreferences.getInstance();sp.setString('roster',jsonEncode(roster));sp.setString('note',jsonEncode(rosterNote));sp.setString('defs',jsonEncode(defs.map((k,v)=>MapEntry(k,v.toJson()))));sp.setString('pattern',jsonEncode(pattern));sp.setDouble('carry',carry);sp.setString('cName',customName);sp.setString('savedPatterns',jsonEncode(savedPatterns));sp.setDouble('stdWeek',standardWeeklyHours);}
int isoWeek(DateTime d){var jan1=DateTime(d.year,1,1);return 1+((d.difference(jan1).inDays+jan1.weekday-1)/7).floor();}
void quickJumpMonth(){int y=focused.year;int m=focused.month;showDialog(context:context,builder:(ctx){return StatefulBuilder(builder:(ctx2,setD){return AlertDialog(title:const Text('快速查找年月'),content:Column(mainAxisSize:MainAxisSize.min,children:[Row(children:[IconButton(icon:const Icon(Icons.remove),onPressed:()=>setD(()=>y--)),Expanded(child:Text('$y年',textAlign:TextAlign.center,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold))),IconButton(icon:const Icon(Icons.add),onPressed:()=>setD(()=>y++))]),Wrap(spacing:8,children:List.generate(12,(i){int mon=i+1;bool sel=mon==m;return ChoiceChip(label:Text('${mon}月'),selected:sel,onSelected:(_)=>setD(()=>m=mon));})]),actions:[TextButton(onPressed:()=>Navigator.pop(ctx2),child:const Text('取消')),FilledButton(onPressed:(){setState(()=>focused=DateTime(y,m,1));Navigator.pop(ctx2);},child:const Text('跳轉'))]);});});}
Widget calTab(){DateTime first=DateTime(focused.year,focused.month,1);DateTime start=first.subtract(Duration(days:first.weekday-1));List<DateTime> days=List.generate(42,(i)=>start.add(Duration(days:i)));String selKey=DateFormat('yyyy-MM-dd').format(selectedDay);var selDef=roster[selKey]!=null?defs[roster[selKey]]:null;return SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(12,8,12,4),child:Row(children:[const Icon(Icons.calendar_month,size:22),const SizedBox(width:8),InkWell(onTap:quickJumpMonth,child:Row(children:[Text('${focused.year}年${focused.month}月',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const Icon(Icons.arrow_drop_down)])),const Spacer(),IconButton(icon:const Icon(Icons.chevron_left),onPressed:(){setState(()=>focused=DateTime(focused.year,focused.month-1,1));}),IconButton(icon:const Icon(Icons.chevron_right),onPressed:(){setState(()=>focused=DateTime(focused.year,focused.month+1,1));}),FilledButton.tonal(onPressed:(){setState((){focused=DateTime.now();selectedDay=DateTime.now();});},child:const Text('今天'))])),Expanded(child:GridView.builder(padding:const EdgeInsets.all(6),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:7,childAspectRatio:0.75,mainAxisSpacing:6,crossAxisSpacing:6),itemCount:42,itemBuilder:(ctx,idx){DateTime day=days[idx];bool inM=day.month==focused.month;String k=DateFormat('yyyy-MM-dd').format(day);String? code=roster[k];var def=code!=null?defs[code]:null;bool sel=k==selKey;String w=idx%7==0?'W${isoWeek(day)}':'';String? hol=hkHolidays[k];Color bg=!inM?const Color(0xFFF5F5F0):hol!=null?const Color(0xFFFFEBEE):sel?Colors.white:def!=null?def.color.withOpacity(0.15):const Color(0xFFFFF0D0);if(code=='O')bg=const Color(0xFFE0F2E9);return GestureDetector(onTap:(){setState(()=>selectedDay=day);showDetail(day);},child:Container(decoration:BoxDecoration(color:bg,borderRadius:BorderRadius.circular(16),border:sel?Border.all(width:2,color:Colors.deepPurple):hol!=null?Border.all(width:1,color:Colors.red.shade200):null),child:Stack(children:[if(w.isNotEmpty)Positioned(left:6,top:4,child:Text(w,style:const TextStyle(fontSize:8,fontWeight:FontWeight.bold,color:Colors.brown))),if(hol!=null)Positioned(right:4,top:4,child:Container(width:6,height:6,decoration:const BoxDecoration(color:Colors.red,shape:BoxShape.circle))),Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text('${day.day}',style:TextStyle(fontWeight:FontWeight.bold,fontSize:14,color:inM?hol!=null?Colors.red:Colors.black:Colors.grey)),if(hol!=null)Text(hol,style:const TextStyle(fontSize:7,color:Colors.red),overflow:TextOverflow.ellipsis),if(code!=null)Container(margin:const EdgeInsets.only(top:2),padding:const EdgeInsets.symmetric(horizontal:7,vertical:2),decoration:BoxDecoration(color:def?.color??Colors.orange,borderRadius:BorderRadius.circular(10)),child:Text(code,style:const TextStyle(color:Colors.white,fontSize:11)))]))]))); })),
Container(padding:const EdgeInsets.fromLTRB(12,8,12,12),decoration:BoxDecoration(color:Colors.white,border:Border(top:BorderSide(color:Colors.grey.shade200))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text('${DateFormat('MM/dd EEE').format(selectedDay)} ${hkHolidays[selKey]??''}',style:const TextStyle(fontSize:14,fontWeight:FontWeight.bold))),if(selDef!=null)Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:3),decoration:BoxDecoration(color:selDef.color,borderRadius:BorderRadius.circular(12)),child:Text(roster[selKey]??'',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.bold)))]),if(selDef!=null)Padding(padding:const EdgeInsets.only(top:4),child:Text('班次:${selDef.label} | 工時:${selDef.hours}h | OT:${selDef.ot}h | 津貼:\$${selDef.allowance} | 記事:${rosterNote[selKey]??'無'}',style:const TextStyle(fontSize:12))),SizedBox(width:double.infinity,child:OutlinedButton.icon(onPressed:(){showDetail(selectedDay);},icon:const Icon(Icons.edit,size:16),label:const Text('編輯此日')))])),
]));}
void showDetail(DateTime day){String k=DateFormat('yyyy-MM-dd').format(day);String cur=roster[k]??'';var nc=TextEditingController(text:rosterNote[k]??'');showModalBottomSheet(context:context,isScrollControlled:true,builder:(ctx){return StatefulBuilder(builder:(ctx2,setM){return Padding(padding:EdgeInsets.only(bottom:MediaQuery.of(ctx2).viewInsets.bottom),child:Padding(padding:const EdgeInsets.all(16),child:Column(mainAxisSize:MainAxisSize.min,children:[Row(children:[Text(DateFormat('yyyy-MM-dd EEE').format(day),style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const Spacer(),if(hkHolidays[k]!=null)Text(hkHolidays[k]!,style:const TextStyle(color:Colors.red))]),Wrap(spacing:8,children:defs.keys.map((c)=>ChoiceChip(label:Text(c),selected:cur==c,onSelected:(_)=>setM(()=>cur=c))).toList()),if(cur.isNotEmpty&&defs[cur]!=null)Container(padding:const EdgeInsets.all(8),decoration:BoxDecoration(color:Colors.grey.shade100,borderRadius:BorderRadius.circular(8)),child:Text('工時:${defs[cur]!.hours}h 津貼:\$${defs[cur]!.allowance} OT:${defs[cur]!.ot}h')),TextField(controller:nc,decoration:const InputDecoration(labelText:'記事 超時工作')),Row(children:[Expanded(child:OutlinedButton(onPressed:(){setState((){roster.remove(k);rosterNote.remove(k);});save();Navigator.pop(ctx2);},child:const Text('清除'))),const SizedBox(width:8),Expanded(child:FilledButton(onPressed:(){setState((){if(cur!=''){roster[k]=cur;rosterNote[k]=nc.text;}});save();Navigator.pop(ctx2);},child:const Text('儲存')))])])));});});}
Future<void> pickRangeAndApply() async{try{DateTimeRange? picked=await showDateRangePicker(context:context,initialDateRange:DateTimeRange(start:DateTime(focused.year,focused.month,1),end:DateTime(focused.year,focused.month+1,0)),firstDate:DateTime(2023),lastDate:DateTime(2030));if(picked==null)return;List<String> flat=pattern.expand((e)=>e).toList();if(flat.isEmpty)return;setState((){int idx=0;for(DateTime d=picked.start;!d.isAfter(picked.end);d=d.add(const Duration(days:1))){roster[DateFormat('yyyy-MM-dd').format(d)]=flat[idx%flat.length];idx++;}});save();setState(()=>tab=0);}catch(e){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('失敗 $e')));}}
void saveCurrentPattern(){var c=TextEditingController(text:'模式${savedPatterns.length+1}');showDialog(context:context,builder:(ctx)=>AlertDialog(title:const Text('獨立存儲模式'),content:TextField(controller:c),actions:[FilledButton(onPressed:(){setState(()=>savedPatterns.add({'name':c.text,'data':pattern.map((r)=>List<String>.from(r)).toList()}));save();Navigator.pop(ctx);},child:const Text('儲存'))]));}
Widget patternTab(){return SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.all(12),child:Row(children:[const Text('排更模式',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const Spacer(),FilledButton.tonal(onPressed:(){setState(()=>pattern.add(List.filled(7,'O')));save();},child:const Text('加一行')),FilledButton.tonal(onPressed:saveCurrentPattern,child:const Text('存儲'))])),Expanded(child:ListView.builder(itemCount:pattern.length,itemBuilder:(ctx,r){return Row(children:[SizedBox(width:24,child:Text('${r+1}')),Expanded(child:Row(children:List.generate(7,(c){String code=pattern[r][c];var d=defs[code];return Expanded(child:GestureDetector(onTap:(){showModalBottomSheet(context:context,builder:(ctx){return Wrap(children:defs.keys.map((k)=>ListTile(title:Text(k),onTap:(){setState(()=>pattern[r][c]=k);save();Navigator.pop(ctx);})).toList());});},child:Container(margin:const EdgeInsets.all(2),height:40,decoration:BoxDecoration(color:d!=null?d.color.withOpacity(0.3):Colors.white,border:Border.all(color:Colors.grey.shade300),borderRadius:BorderRadius.circular(8)),child:Center(child:Text(code)))));}))),IconButton(icon:const Icon(Icons.delete),onPressed:(){setState(()=>pattern.removeAt(r));save();})]);})),Padding(padding:const EdgeInsets.all(12),child:Column(children:[Row(children:[Expanded(child:OutlinedButton.icon(onPressed:(){showModalBottomSheet(context:context,builder:(ctx){return ListView(children:[...savedPatterns.asMap().entries.map((e)=>ListTile(title:Text(e.value['name']),onTap:(){setState(()=>pattern=(e.value['data'] as List).map<List<String>>((r)=>(r as List).map<String>((x)=>x.toString()).toList()).toList());save();Navigator.pop(ctx);})),ListTile(title:const Text('關閉'),onTap:()=>Navigator.pop(ctx))]);});},icon:const Icon(Icons.folder),label:const Text('已存模式')))]),const SizedBox(height:8),SizedBox(width:double.infinity,height:50,child:FilledButton.icon(onPressed:pickRangeAndApply,icon:const Icon(Icons.date_range),label:const Text('選擇日期範圍並自動排班')))]))]));
}
Widget reportTab(){int dim=DateTime(focused.year,focused.month+1,0).day;Map<String,int> cnt={};double hrs=0,allow=0,ot=0;Map<String,double> allowByCode={};Map<int,double> weeklyHours={};for(int i=1;i<=dim;i++){DateTime dt=DateTime(focused.year,focused.month,i);String k=DateFormat('yyyy-MM-dd').format(dt);String? c=roster[k];if(c==null)continue;cnt[c]=(cnt[c]??0)+1;var d=defs[c];if(d!=null){hrs+=d.hours;allow+=d.allowance;ot+=d.ot;allowByCode[c]=(allowByCode[c]??0)+d.allowance;int w=isoWeek(dt);weeklyHours[w]=(weeklyHours[w]??0)+d.hours;}}return SafeArea(child:ListView(padding:const EdgeInsets.all(12),children:[Text('${focused.year}年${focused.month}月 報表',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('班次資料',style:TextStyle(fontWeight:FontWeight.bold)),...cnt.entries.map((e){var d=defs[e.key];return Row(children:[Text('${e.key} ${d?.label??''}'),const Spacer(),Text('x${e.value} ${d!=null?'${(d.hours*e.value).toStringAsFixed(1)}h / \$${(d.allowance*e.value).toStringAsFixed(1)}':''}')]);})]))),Card(color:const Color(0xFFE3F2FD),child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('每週工時與差額 (標準44h)',style:TextStyle(fontWeight:FontWeight.bold)),...weeklyHours.entries.map((e){double diff=e.value-standardWeeklyHours;return Row(children:[Text('W${e.key}'),const Spacer(),Text('${e.value.toStringAsFixed(1)}h'),SizedBox(width:12,child:Text('${diff>=0?'+':''}${diff.toStringAsFixed(1)}',style:TextStyle(color:diff>0?Colors.red:Colors.green)))]);}),Divider(),Text('總工時 ${hrs.toStringAsFixed(1)}h')]))),Card(color:const Color(0xFFE8F5E9),child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('津貼類別',style:TextStyle(fontWeight:FontWeight.bold)),...allowByCode.entries.map((e)=>Row(children:[Text(e.key),Spacer(),Text('\$${e.value.toStringAsFixed(1)}')])),Divider(),Text('總津貼 \$${allow.toStringAsFixed(1)} OT ${ot.toStringAsFixed(1)}h')])))]));}
Future<void> backupLocalFile() async{var dir=await getApplicationDocumentsDirectory();var f=File('${dir.path}/roster_backup.json');await f.writeAsString(jsonEncode({'roster':roster,'note':rosterNote,'defs':defs.map((k,v)=>MapEntry(k,v.toJson())),'pattern':pattern,'carry':carry,'cName':customName,'savedPatterns':savedPatterns}));ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('已備份 ${f.path}')));}
Future<void> restoreLocalFile() async{var res=await FilePicker.platform.pickFiles(type:FileType.custom,allowedExtensions:['json']);if(res==null)return;String c=await File(res.files.single.path!).readAsString();var j=jsonDecode(c);setState((){roster=Map<String,String>.from(j['roster']);rosterNote=Map<String,String>.from(j['note']);customName=j['cName'];nameCtrl.text=customName;});save();}
Future<void> exportICS() async{var dir=await getApplicationDocumentsDirectory();var f=File('${dir.path}/$customName.ics');await f.writeAsString('BEGIN:VCALENDAR');ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('已匯出 ${f.path}')));}
Widget settingsTab(){return SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[const Text('自定班次',style:TextStyle(fontWeight:FontWeight.bold)),Card(child:Column(children:[...defs.entries.map((e){var d=e.value;return ListTile(title:Text('${d.code} ${d.label}'),subtitle:Text('\$${d.allowance} ${d.hours}h'),trailing:IconButton(icon:const Icon(Icons.edit),onPressed:(){var cc=TextEditingController(text:d.code);var lc=TextEditingController(text:d.label);var hc=TextEditingController(text:d.hours.toString());var ac=TextEditingController(text:d.allowance.toString());showDialog(context:context,builder:(ctx)=>AlertDialog(title:const Text('編輯'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:cc,decoration:const InputDecoration(labelText:'代碼')),TextField(controller:lc,decoration:const InputDecoration(labelText:'名稱')),TextField(controller:hc,decoration:const InputDecoration(labelText:'工時'),keyboardType:TextInputType.number),TextField(controller:ac,decoration:const InputDecoration(labelText:'津貼支援小數'),keyboardType:const TextInputType.numberWithOptions(decimal:true))]),actions:[FilledButton(onPressed:(){setState(()=>defs[e.key]=ShiftDef(cc.text,lc.text,double.tryParse(hc.text)??8,Colors.orange,allowance:double.tryParse(ac.text)??0));save();Navigator.pop(ctx);},child:const Text('儲存'))]));}));}),ListTile(title:const Text('新增'),onTap:(){var cc=TextEditingController();showDialog(context:context,builder:(ctx)=>AlertDialog(title:const Text('新增'),content:TextField(controller:cc),actions:[FilledButton(onPressed:(){setState(()=>defs[cc.text]=ShiftDef(cc.text,cc.text,8,Colors.orange));save();Navigator.pop(ctx);},child:const Text('加'))]));})])),
Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(children:[TextField(controller:nameCtrl,decoration:const InputDecoration(labelText:'日曆名稱 例如 HING')),Row(children:[Expanded(child:Text('現時：$customName')),FilledButton(onPressed:(){setState(()=>customName=nameCtrl.text.trim().isEmpty?'我的排更':nameCtrl.text.trim());save();ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('已設定為 $customName')));},child:const Text('確認'))])]))),
Card(child:ListTile(title:const Text('備份'),subtitle:Row(children:[TextButton(onPressed:backupLocalFile,child:const Text('備份到手機')),TextButton(onPressed:restoreLocalFile,child:const Text('還原'))]))),
]));}
@override Widget build(BuildContext context){return Scaffold(body:[calTab(),patternTab(),reportTab(),settingsTab()][tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.calendar_month),label:'月曆'),NavigationDestination(icon:Icon(Icons.pattern),label:'模式'),NavigationDestination(icon:Icon(Icons.bar_chart),label:'報表'),NavigationDestination(icon:Icon(Icons.settings),label:'設定')]));}
}
